[features]
seeds = false
skip-lint = false
[programs.localnet]
# frontier = "Fk8C6UUGGZgWHXmb6HPHNhfnBhf4eKDzNnj4R8zMjHCr"
frontier = "3FKoVbicsX7moGuqVPCY1qkZ4adA85tTpYVFEe9Vs2ei"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/kyle/.config/solana/id.json"

[scripts]
test = "yarn run jest --preset ts-jest"
