[features]
seeds = false
skip-lint = false
[programs.localnet]
clash_of_clones = "Fk8C6UUGGZgWHXmb6HPHNhfnBhf4eKDzNnj4R8zMjHCr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/kyle/.config/solana/id.json"

[scripts]
test = "yarn run jest --preset ts-jest"
